- .vscode/launch.json
Run the project locally on specific port 8000 so we don't have to authenticate every time we run the app. This is caused because secure storage package is storing data for specific port and domain
> Chore: run-project-on-specific-port

- .github/workflows/cd-dev.yaml
- .github/workflows/cd-prd.yaml
- .github/workflows/cd-stg.yaml
> ci(cd): fix cd

- lib/app/dependency_injection/init.config.dart
- lib/app/routes/router/app_router.dart
- lib/app/routes/router/app_router.gr.dart
- lib/app/view/initial_page.dart
- lib/integrations/presentation/pages/integrate_with_platform_page.dart
Implements new basic route for accepting oauth callback redirects detecting the platform and the code from the url
> feat(routes): create new route for receving platform and code

- lib/app/dependency_injection/init.config.dart
- lib/core/module/core_module.dart
- lib/integrations/presentation/pages/integrate_with_platform_page.dart
- lib/integrations/presentation/pages/integrations_page.dart
- lib/integrations/state_management/integrations_repository/integrations_cubit.dart
- lib/integrations/state_management/integrations_repository/integrations_state.dart
- packages/integrations_repository/lib/src/entities/integration/integration.dart
- packages/integrations_repository/lib/src/integrations_repository.dart
- pubspec.lock
- pubspec.yaml
Implements page that captures oAuth data and integrates with platform
> feat(integrations): handle callback url and add event to cubit to integrate with platoform

- lib/app/dependency_injection/init.config.dart
- lib/blueprint/module/blueprint_module.dart
- lib/blueprint/presentation/pages/todays_blueprint.dart
- packages/blueprint_repository/build.yaml
- packages/blueprint_repository/lib/src/blueprint_repository.dart
- packages/blueprint_repository/lib/src/entities/calendar_event.dart
- packages/blueprint_repository/lib/src/entities/calendar_event.freezed.dart
- packages/blueprint_repository/lib/src/entities/calendar_event.g.dart
- packages/calendar_repository/build.yaml
- packages/calendar_repository/lib/src/entities/event.g.dart
- packages/calendar_repository/lib/src/entities/meeting_data.g.dart
- packages/task_repository/build.yaml
- packages/task_repository/lib/src/entities/project/project.g.dart
- packages/task_repository/lib/src/entities/task/task.g.dart
- packages/task_repository/pubspec.yaml
Create a build.yaml file for all the repositories that contain models and also fix the issues with the blueprint_repository that were not properly working.
There are some presentation files that are not meant to be in this PR, they are just there for guidance for next work
> refactor(blueprint_repository): add explicitToJson to all repositories models 

- lib/integrations/presentation/pages/integrate_with_platform_page.dart
- lib/integrations/state_management/integrations_repository/integrations_cubit.dart
- lib/integrations/state_management/integrations_repository/integrations_cubit.freezed.dart
- lib/integrations/state_management/integrations_repository/integrations_state.dart
Fixes integrations page by creating a new separate state to show an integration was just made and react to that state on the UI to pop the page. Also handles this state on the builder function with a nice message to the user asking the user to close page.
> fix: platform integrations page

- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
Update firebase dependencies to latest versions
> build(pubspec): upgrade firebase dependencies to use latest stuff

- lib/app/dependency_injection/init.config.dart
- lib/blueprint/module/blueprint_module.dart
- lib/blueprint/state_management/blueprint_bloc/blueprint_bloc.dart
- lib/blueprint/state_management/blueprint_bloc/blueprint_event.dart
- lib/blueprint/state_management/blueprint_bloc/blueprint_state.dart
- packages/blueprint_repository/lib/src/blueprint_repository.dart
- packages/blueprint_repository/test/src/blueprint_repository_test.dart
- pubspec.lock
- pubspec.yaml
- test/blueprint/blueprint_bloc/blueprint_bloc_test.dart
- test/blueprint/blueprint_bloc/blueprint_event_test.dart
- test/blueprint/blueprint_bloc/blueprint_state_test.dart
> feat: feat/blueprint bloc

- functions/.gitignore
- functions/package.json
> build: change functions entrypoint in package.json

- .gitignore
- functions/.gitignore
- functions/package.json
- functions/src/modules/events/domain/entities/conference-data.entity.ts
- functions/src/modules/events/domain/entities/event.entity.ts
- functions/src/modules/events/domain/entities/user.entity.ts
- functions/src/modules/events/domain/usecases/__mocks__/event.mock.ts
- functions/src/modules/events/infrastructure/repositories/local/converters/event.converter.ts
- functions/src/modules/events/infrastructure/repositories/remote/base.event.remote.repository.ts
- functions/src/modules/events/infrastructure/repositories/remote/mappers/google-calendar.mapper.ts
- functions/src/modules/tasks/infrastructure/services/jira.service.ts
- lib/app/dependency_injection/init.config.dart
- lib/calendar/presentation/views/event_details.dart
- packages/calendar_repository/lib/src/entities/event.dart
- packages/calendar_repository/lib/src/entities/event.g.dart
- packages/calendar_repository/lib/src/entities/user_with_status.dart
- packages/calendar_repository/lib/src/entities/user_with_status.g.dart
Save Google-Calendar conference details to Firestore
> fix(events): add gcal conference details data

- lib/app/dependency_injection/init.config.dart
- lib/app/routes/guards/authentication_guard.dart
- lib/app/routes/router/app_router.dart
- lib/app/routes/router/app_router.gr.dart
- lib/authentication/presentation/pages/forgot_password_screen.dart
- lib/authentication/presentation/pages/sign_in_page.dart
- lib/core/l10n/arb/app_en.arb
- lib/core/l10n/arb/app_es.arb
- packages/app_ui/lib/src/widgets/block_dialog.dart
- packages/app_ui/lib/src/widgets/list_tile.dart
- packages/app_ui/lib/src/widgets/widgets.dart
> feat: forgot password screen

- functions/src/modules/events/domain/usecases/__mocks__/event.mock.ts
- functions/src/modules/users/users.module.ts
Add trigger onDelete for deleting users from userCollection when auth deletes a user
> feat(users.module): add trigger to delete user on cascade

- lib/users/presentation/widgets/profile_menu.dart
Remove extra positioned widget that causes crash in the app
> fix: user profile menu

- lib/tasks/state_management/cubit/tasks_cubit.dart
- packages/task_repository/lib/src/entities/entities.dart
- packages/task_repository/lib/src/entities/sort_by/sort_by.dart
- packages/task_repository/lib/src/task_repository.dart
- packages/task_repository/pubspec.yaml
Supports filtering by different fields and sort by. This changes introduce big tech debt, since this should be addressed on the backend side or at least in a data layer, querying the database with the filters already added, but since we are using Firebase, text search is going to be complicated. We will have to create a new field on the tasks with all the fields that could match a searching, or using an external search engine like Elastic Search or something similar. 
For now, we are going to release MVP with the fetch of all the tasks, and the filtering done on the client side.
> feat(task_repository): support filter and sortBy operations

- lib/app/view/initial_page.dart
- lib/blueprint/presentation/pages/blueprint_timeline.dart
- lib/blueprint/presentation/pages/todays_blueprint.dart
- lib/blueprint/presentation/widgets/calendar_event_tile.dart
- lib/blueprint/presentation/widgets/create_event_dialog.dart
- lib/blueprint/state_management/blueprint_bloc/blueprint_bloc.dart
- lib/blueprint/state_management/blueprint_bloc/blueprint_state.dart
- lib/calendar/presentation/widgets/available_time_card.dart
- lib/calendar/presentation/widgets/event_card.dart
- lib/calendar/presentation/widgets/widgets.dart
- lib/core/l10n/arb/app_en.arb
- lib/main_local.dart
- lib/tasks/presentation/pages/tasks_page.dart
- lib/tasks/presentation/widgets/task_card.dart
- packages/app_ui/lib/src/widgets/blueprint_event_card.dart
- packages/app_ui/lib/src/widgets/list_tile.dart
- packages/app_ui/lib/src/widgets/timeline.dart
- packages/app_ui/lib/src/widgets/widgets.dart
- packages/app_ui/storybook/lib/stories/component/components.dart
- packages/app_ui/storybook/lib/stories/component/event_card.dart
- packages/app_ui/storybook/lib/stories/component/todays_timeline.dart
- packages/blueprint_repository/lib/src/blueprint_repository.dart
- test/app/view/app_test.dart
> feat: implement updated UI for the todays blueprint page

- functions/src/modules/blueprint/infrastructure/repositories/firestore-blueprint-local.repository.ts
> fix(firestore-blueprint-local.repository): update startTime and endTime for blueprint events on update 

- functions/src/modules/events/interfaces/scheduler/scheduler.ts
- functions/src/modules/tasks/infrastructure/controllers/refresh-tasks.controller.ts
- functions/src/modules/tasks/interfaces/scheduler/scheduler.ts
Fixes refresh token by catching error and also changes time for scheduler to run every 1 minute
> fix: refresh token

- functions/src/modules/events/infrastructure/repositories/remote/google-calendar.event.remote.repository.ts
Pull google calendar events from the beginning of the day
> feat(events): pull gcal events form start of the day

- functions/src/modules/tasks/infrastructure/services/jira.service.ts
- Fix Jira user links
- Retrieve only not-completed issues from Jira
- Add complete description as an HTML
> fix(jira): fix user web link and retrieve only not-done tasks

- packages/app_ui/lib/src/widgets/timeline.dart
- packages/app_ui/lib/src/widgets/timeline_settings.dart
- packages/app_ui/lib/src/widgets/widgets.dart
Implemnents a new interface for timeline settings with a better UX
> feat(timeline_settings): implement a better solution for timeline settings for view and density

- firebase.json
- packages/ai_client/lib/src/clients/chat_gpt_client.dart
- packages/ai_client/pubspec.yaml
- pubspec.lock
- pubspec.yaml
> fix: update chat_gpt sdk and correctly migrate to v2

- lib/ai_assistant_chat/state_management/bloc/ai_assistant_chat_bloc.dart
- packages/blueprint_repository/lib/src/blueprint_repository.dart
- packages/blueprint_repository/lib/src/converter/timestamp_converter.dart
> fix: minor changes to ai scheduling

- functions/src/modules/events/infrastructure/repositories/remote/google-calendar.event.remote.repository.ts
- packages/calendar_repository/lib/src/utils/timestamp_converter.dart
- packages/integrations_repository/lib/src/utils/timestamp_converter.dart
- packages/task_repository/lib/src/utils/timestamp_converter.dart
> fix: timestamps converters

- .github/workflows/cd-dev.yaml
- functions/src/modules/events/infrastructure/repositories/remote/google-calendar.event.remote.repository.ts
- packages/calendar_repository/lib/src/utils/timestamp_converter.dart
- packages/integrations_repository/lib/src/utils/timestamp_converter.dart
- packages/task_repository/lib/src/utils/timestamp_converter.dart
> fix: timestamps

- lib/authentication/presentation/pages/sign_up_page.dart
- lib/core/l10n/arb/app_en.arb
- lib/core/l10n/arb/app_es.arb
Fix signUp page text for sign in
> fix: sign in text
